# Generated by Django 3.1.2 on 2020-10-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrants',
            new_name='Registrant',
        ),
    ]
